scrape_configs:
  - job_name: 'MonitoringDemo'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['be:8080']
        labels:
          application: 'MonitoringDemo Application'
